name: Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  Client:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm run test:ci

      - name: Build
        run: npm run build

  Server:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run Server
        run: npm test